name: example-environment
dependencies:
  - python=3.7.6
  - pip
  - pip:
    - opencv-python-headless==4.5.3.56
    - matplotlib==3.4.3
    - numpy==1.21.2
    - pillow==7.0.0
    - bokeh==2.1.1
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.63.0
    - ipywidgets
    - notebook
    - livelossplot==0.5.4
    - pytest==7.1.1
    - pandas==1.3.5
    - seaborn==0.11.2
