name: example-environment
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - torch
  - torchvision
